### ISSUE TITLE
Reference publication for Giskard?

### ISSUE THREAD

**Issue by rhaschke** [SemRoCo/giskardpy#102]
Could you please refer in your README file to (the) reference publication(s) introducing/describing Giskard? I had a hard-time finding anything, because Giskard is probably not mentioned in the original paper title.
I found this one: https://ai.uni-bremen.de/papers/fang16simcontrol.pdf

**Comment by ichumuh** [comment]
The one you linked is probably the closest we have at the moment, but it is still quite far away from what Giskard is now. We have a publication which got accepted at IROS though. I'll add it once it's out.

**Comment by rhaschke** [comment]
Just to be sure: this repo (`giskardpy`) superseeds [`giskard_core`](https://github.com/SemRoCo/giskard_core) and [`giskard_ros`](https://github.com/SemRoCo/giskard_ros), right?
What are the control cycle rates you can achieve with the python implementation?

**Comment by ichumuh** [comment]
Yes, the giskardpy implementation is independent of giskard_core and giskard_ros. Those are the old cpp implementation described in the paper you linked.
The optimization problems I'm building are sometimes too large for real time control, depending on what the goal combination is, which is why I integrate the commands to generate trajectories, which are then send to follow traj controller(s) of the robot.
On my devel branch, I'm experimenting with controlling a robot's base via the /cmd_vel topic in real time, by setting up a smaller optimization problem to follow the precomputed trajectory for the base in sync with the follow traj controller(s) of the rest of the robot. This manages ~30hz at the moment.

**Comment by rhaschke** [comment]
Thanks for sharing this information and paper. I will leave this issue open as a reminder to add the paper to the README later.
