### ISSUE TITLE
License

### ISSUE THREAD

**Issue by airballking** [SemRoCo/giskardpy#2]
We have to choose a license. As a first step, we should assemble a list of license of our dependencies, and take it from there. @amaldo would you have time to consult us in this process?

**Comment by amaldo** [comment]
Hi,

After talking with Georg today, I would recommend the LGPLv3.

https://tldrlegal.com/license/gnu-lesser-general-public-license-v3-%28lgpl-3%29

It is compatible with Apache 2.0 and BSD ( and zlib license used in pybullet).

The other option for me would be GPLv3. The only difference is that if a company would like the giskard code into their own code, they would have to make their own code GPLv3 too. In the world of programming using middlewares (that are usually BSD licensed) this is not a big issue anymore because you typically don't link together.

By using the LGPL companies would be free to write code that links to giskard directly, and they only have to release the changes to giskard if they release a product/software with it.

Have a nice day,

Alexis
